import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { TooltipProvider } from '@/components/ui/tooltip';
import { Toaster } from '@/components/ui/toaster';
import { ArrowUpRight, Instagram, Mail, Menu, Send, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import logoAsset from '@assets/ChatGPT_Image_Mar_23,_2026,_05_44_13_PM_1784895702051.png';
import portraitAsset from '@assets/Jul_8,_2026,_08_10_16_PM_1784895778584.png';
import stillStandingAsset from '@assets/1776530334_1784898602310.png';
import stillHealingAsset from '@assets/Still_healing_1784898618900.jpg';
import stillWorthyAsset from '@assets/Still_worthy_1784898634719.png';
import stillBreathingAsset from '@assets/Still_Breathing_1784898655352.jpg';
import stillRisingAsset from '@assets/Still_rising_1784898677868.png';

const queryClient = new QueryClient();
type Book = { title: string; subtitle: string; description: string; image: string; color: string; accent: string; label: string; detail: string };
const books: Book[] = [
  { title: 'Still Standing', subtitle: 'Finding Love, Worth and Healing in Your Hardest Seasons', description: 'A compassionate guide for navigating heartbreak, disappointment, loss, and emotional pain — an invitation to move forward with hope, courage, and self-worth.', image: stillStandingAsset, color: '#354052', accent: '#f4eee7', label: 'Book one · Still Standing series', detail: 'Still Standing reminds readers that healing is not about becoming who you were before, but discovering the strength to move forward with hope, courage, and self-worth.' },
  { title: 'Still Healing', subtitle: '30 Days of Deep Healing, One Lesson at a Time', description: 'A 30-day guided journey with thoughtful insights, practical exercises, affirmations, and gentle encouragement for emotional healing and personal growth.', image: stillHealingAsset, color: '#e6cda9', accent: '#702b22', label: 'Guided journey', detail: 'A steady companion for recovering from heartbreak, grief, disappointment, or simply learning to embrace yourself again.' },
  { title: 'Still Worthy', subtitle: 'Reclaiming Your Worth, One Truth at a Time', description: 'Honest reflections and empowering truths to help you let go of self-doubt, rebuild confidence, and live from a place of self-respect.', image: stillWorthyAsset, color: '#260508', accent: '#e2b94d', label: 'Reflections', detail: 'Your worth has never depended on what you have been through, what you have lost, or what others have said about you.' },
  { title: 'Still Breathing', subtitle: 'Finding Peace, Calm and Presence After Life Has Knocked the Breath Out of You', description: 'A gentle reminder that even in the middle of life’s storms, peace is still possible — one breath and one moment of calm at a time.', image: stillBreathingAsset, color: '#122c28', accent: '#f5f2ea', label: 'A calming companion', detail: 'For anyone seeking hope, presence, and the courage to take the next breath through anxiety, grief, and emotional overwhelm.' },
  { title: 'Still Rising', subtitle: 'Rebuilding, Reclaiming, Stepping Into Your Full Life', description: 'A future release about rebuilding, reclaiming, and stepping fully into the life that is still possible.', image: stillRisingAsset, color: '#4a3b51', accent: '#f4bb65', label: 'Future release', detail: 'Roselyn continues to write books exploring healing, resilience, emotional well-being, and personal growth. Stay connected for updates.' },
];
const navItems = [['Home', 'top'], ['Books', 'books'], ['Meet Roselyn', 'about'], ['Journal', 'journal'], ['Gather', 'gather']];
function scrollToSection(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function BookCover({ book, small = false }: { book: Book; small?: boolean }) {
  return <div className={`relative overflow-hidden border border-[#efe5db] shadow-[16px_24px_38px_-22px_rgba(60,42,34,.5)] transition-transform duration-500 group-hover:-translate-y-2 ${small ? 'h-[210px] w-[144px]' : 'h-[390px] w-[260px]'}`} style={{ background: book.color }} aria-label={`${book.title} book cover`}><img src={book.image} alt={`${book.title} by Roselyn Gifford`} className="h-full w-full object-contain" /></div>;
}
function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeBook, setActiveBook] = useState<Book | null>(null);
  const [newsletter, setNewsletter] = useState('');
  const [newsletterSent, setNewsletterSent] = useState(false);
  const [messageSent, setMessageSent] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 24); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll); }, []);
  const go = (id: string) => { setMenuOpen(false); scrollToSection(id); };
  return <QueryClientProvider client={queryClient}><TooltipProvider><div className="grain min-h-[100dvh] overflow-hidden bg-[#fbf8f4] text-[#3c2a22]">
     <header className={`fixed inset-x-0 top-0 z-20 transition-all duration-300 ${scrolled ? 'border-b border-[#e7ddd2]/80 bg-[#fbf8f4]/90 shadow-[0_8px_30px_-22px_rgba(60,42,34,.7)] backdrop-blur-md' : 'bg-transparent'}`}><div className="mx-auto flex max-w-[1240px] items-center justify-between px-6 py-5 lg:px-12"><button onClick={() => go('top')} className="flex items-center gap-3 text-left" data-testid="button-brand-home" aria-label="Return to the top"><img src={logoAsset} alt="Gifford Publishing mark" className="h-10 w-10 rounded-full object-cover" /><span className="font-serif text-[17px] leading-none tracking-tight">Roselyn Gifford</span></button><nav className="hidden items-center gap-7 md:flex" aria-label="Primary navigation">{navItems.map(([label, id]) => <button key={id} onClick={() => go(id)} className="font-mono text-[10px] uppercase tracking-[.13em] text-[#72655a] transition-colors hover:text-[#b76872]" data-testid={`link-nav-${id}`}>{label}</button>)}<button onClick={() => go('contact')} className="border-b border-[#3c2a22] pb-1 font-mono text-[10px] uppercase tracking-[.13em] transition-colors hover:border-[#b76872] hover:text-[#b76872]">Write to Me</button></nav><button onClick={() => setMenuOpen(!menuOpen)} className="rounded-sm p-2 md:hidden" aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} data-testid="button-mobile-menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div>{menuOpen && <div className="border-t border-[#e7ddd2] bg-[#fbf8f4] px-6 py-7 md:hidden"><div className="flex flex-col gap-5">{navItems.map(([label, id]) => <button key={id} onClick={() => go(id)} className="text-left font-mono text-[11px] uppercase tracking-[.18em] text-[#72655a]" data-testid={`link-mobile-${id}`}>{label}</button>)}<button onClick={() => go('contact')} className="text-left font-mono text-[11px] uppercase tracking-[.18em] text-[#b76872]">Write to Me</button></div></div>}</header>
    <main id="top">
       <section className="relative mx-auto grid min-h-[760px] max-w-[1240px] items-center gap-12 px-6 pb-20 pt-36 lg:grid-cols-[1.02fr_.98fr] lg:px-12 lg:pt-40"><div className="relative z-10 max-w-[620px] reveal"><div className="mb-7 flex items-center gap-4"><span className="eyebrow">Author · Storyteller · Publisher</span><span className="h-px w-12 bg-[#c7a164]" /></div><h1 className="font-serif text-[clamp(52px,8vw,104px)] leading-[.91] tracking-[-.055em]">A story can<br /><em className="font-serif text-[#b76872]">make room</em><br />for hope.</h1><p className="mt-9 max-w-[470px] font-serif text-[19px] leading-[1.65] text-[#72655a]">Books that inspire healing, resilience, and hope through life’s hardest seasons.</p><div className="mt-10 flex flex-wrap items-center gap-5"><button onClick={() => go('books')} className="group flex items-center gap-3 bg-[#3c2a22] px-6 py-4 font-mono text-[10px] uppercase tracking-[.16em] text-[#fbf8f4] transition-colors hover:bg-[#b76872]" data-testid="button-hero-books">Explore the collection <ArrowUpRight size={14} /></button><button onClick={() => go('about')} className="border-b border-[#3c2a22] pb-1 font-mono text-[10px] uppercase tracking-[.16em] hover:border-[#b76872] hover:text-[#b76872]" data-testid="button-hero-about">Meet Roselyn</button></div></div><div className="relative flex min-h-[410px] items-center justify-center lg:min-h-[600px] reveal"><div className="absolute right-[4%] top-[7%] h-[280px] w-[280px] rounded-full border border-[#c7a164]/50 lg:h-[440px] lg:w-[440px]" /><div className="absolute right-[7%] top-[10%] -rotate-12 font-script text-5xl text-[#b76872]/70">stories<br />for the soul</div><div className="relative z-10 rounded-full bg-[#e8d1cc]/55 p-5 lg:p-7"><img src={logoAsset} alt="Gifford Publishing logo" className="h-[310px] w-[310px] rounded-full object-cover shadow-[0_30px_60px_-25px_rgba(60,42,34,.42)] lg:h-[430px] lg:w-[430px]" /></div></div></section>
      <section className="border-y border-[#e7ddd2] bg-[#f7f1e9]"><div className="mx-auto grid max-w-[1240px] gap-8 px-6 py-12 md:grid-cols-3 md:gap-0 md:px-12">{[['01', 'Words with a pulse', 'Stories that meet you where you are, then stay with you.'], ['02', 'A generous view', 'A belief in second chances, quiet courage, and the wisdom of seasons.'], ['03', 'Room to reflect', 'Pages that invite a pause — not a performance.']].map(([number, title, text], i) => <div key={number} className={`flex gap-5 ${i > 0 ? 'border-[#e7ddd2] md:border-l md:pl-9' : ''}`}><span className="font-mono text-[10px] text-[#b76872]">{number}</span><div><h2 className="font-serif text-[20px]">{title}</h2><p className="mt-2 max-w-[270px] text-[14px] leading-6 text-[#72655a]">{text}</p></div></div>)}</div></section>
      <section id="books" className="scroll-mt-20 px-6 py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1240px]"><div className="mb-14 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="eyebrow">The reading room</div><h2 className="mt-4 max-w-[600px] font-serif text-[clamp(38px,5vw,66px)] leading-[.98] tracking-[-.04em]">Books for the<br /><em className="text-[#b76872]">becoming.</em></h2></div><p className="max-w-[310px] text-[14px] leading-6 text-[#72655a]">Novels, reflections, and stories for the season you are living through — and the one you are walking toward.</p></div><div className="grid gap-10 lg:grid-cols-[1.15fr_.85fr]"><div className="group grid items-center gap-9 border-y border-[#e7ddd2] py-10 md:grid-cols-[.75fr_1fr]"><button onClick={() => setActiveBook(books[0])} className="mx-auto block cursor-pointer text-left" data-testid="button-open-book-garden"><BookCover book={books[0]} /></button><div><span className="eyebrow">{books[0].label} · Featured</span><h3 className="mt-4 font-serif text-[34px] leading-tight">{books[0].title}</h3><p className="mt-2 font-serif text-[16px] italic leading-7 text-[#72655a]">{books[0].subtitle}</p><p className="mt-5 text-[14px] leading-7 text-[#72655a]">{books[0].description}</p><button onClick={() => setActiveBook(books[0])} className="mt-6 inline-flex items-center gap-2 border-b border-[#3c2a22] pb-1 font-mono text-[10px] uppercase tracking-[.15em] hover:border-[#b76872] hover:text-[#b76872]" data-testid="button-read-garden">Read about the book <ArrowUpRight size={14} /></button></div></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-1">{books.slice(1).map((book) => <article key={book.title} className="group flex gap-6 border-b border-[#e7ddd2] pb-6"><button onClick={() => setActiveBook(book)} className="shrink-0 cursor-pointer" data-testid={`button-open-book-${book.title.toLowerCase().replaceAll(' ', '-')}`}><BookCover book={book} small /></button><div className="pt-2"><span className="eyebrow">{book.label}</span><h3 className="mt-3 font-serif text-[23px] leading-tight">{book.title}</h3><p className="mt-2 text-[13px] leading-6 text-[#72655a]">{book.description}</p><button onClick={() => setActiveBook(book)} className="mt-3 font-mono text-[9px] uppercase tracking-[.14em] text-[#b76872]" data-testid={`button-details-${book.title.toLowerCase().replaceAll(' ', '-')}`}>View details</button></div></article>)}</div></div><div className="mt-14 flex flex-col items-center justify-between gap-5 border-t border-[#e7ddd2] pt-7 sm:flex-row"><span className="font-script text-3xl text-[#b76872]">Come, stay awhile.</span><button onClick={() => go('journal')} className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.15em] text-[#72655a] hover:text-[#b76872]" data-testid="button-books-journal">Continue to the journal <ArrowUpRight size={14} /></button></div></div></section>
      <section id="about" className="scroll-mt-20 bg-[#eee5da] px-6 py-28 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1100px] items-center gap-16 lg:grid-cols-[.8fr_1.2fr]"><div className="relative mx-auto max-w-[350px]"><div className="absolute -inset-4 border border-[#c7a164]/70" /><img src={portraitAsset} alt="Watercolor portrait of Roselyn Gifford" className="relative aspect-[4/5] w-full object-cover object-top" /><div className="absolute -bottom-7 -right-8 rotate-[-8deg] bg-[#fbf8f4] px-5 py-3 shadow-sm"><span className="font-script text-3xl text-[#b76872]">with heart</span></div></div><div><div className="eyebrow">A note from Roselyn</div><h2 className="mt-5 max-w-[650px] font-serif text-[clamp(38px,5vw,65px)] leading-[1] tracking-[-.045em]">The stories we need<br /><em className="text-[#b76872]">find us.</em></h2><div className="mt-8 max-w-[580px] space-y-4 font-serif text-[17px] leading-8 text-[#72655a]"><p>I have always believed a book can be a kind of lantern. Not because it answers every question, but because it helps us see the next honest step.</p><p>My work lives in the space between what has been lost and what might still be possible. I write about home, self-worth, resilience, and the tender work of choosing ourselves again.</p></div><div className="mt-10 flex flex-wrap gap-8 border-t border-[#d6c8b8] pt-6">{[['Writing toward', 'healing'], ['Rooted in', 'hope'], ['Published by', 'Gifford']].map(([a, b]) => <div key={a}><div className="font-mono text-[9px] uppercase tracking-[.15em] text-[#a58d70]">{a}</div><div className="mt-1 font-serif text-[19px]">{b}</div></div>)}</div><button onClick={() => go('contact')} className="mt-9 inline-flex items-center gap-2 border-b border-[#3c2a22] pb-1 font-mono text-[10px] uppercase tracking-[.15em] hover:border-[#b76872] hover:text-[#b76872]" data-testid="button-about-note">Send a note <ArrowUpRight size={14} /></button></div></div></section>
      <section id="journal" className="scroll-mt-20 px-6 py-28 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1240px]"><div className="mb-14 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="eyebrow">From the journal</div><h2 className="mt-4 font-serif text-[clamp(38px,5vw,64px)] leading-none tracking-[-.04em]">A few words<br /><em className="text-[#b76872]">to keep.</em></h2></div><p className="max-w-[270px] text-[14px] leading-6 text-[#72655a]">Notes on the writing life, the inner life, and the small things that help us return.</p></div><div className="grid gap-6 md:grid-cols-[1.25fr_.75fr_.75fr]"><article className="group relative min-h-[350px] overflow-hidden bg-[#657868] p-8 text-[#fbf8f4] md:row-span-2 md:min-h-[450px]"><div className="absolute -right-9 -top-12 h-52 w-52 rounded-full border border-[#d8c79b]/50" /><div className="relative flex h-full flex-col justify-between"><div><span className="font-mono text-[9px] uppercase tracking-[.18em] text-[#e2d6b8]">Essay · 6 min read</span><h3 className="mt-20 max-w-[430px] font-serif text-[35px] leading-[1.02]">On the days when beginning again feels too big</h3></div><button onClick={() => go('contact')} className="flex w-fit items-center gap-2 border-b border-[#e2d6b8] pb-1 font-mono text-[10px] uppercase tracking-[.15em] text-[#e2d6b8]" data-testid="button-journal-feature">Read the reflection <ArrowUpRight size={14} /></button></div></article><article className="border-t border-[#e7ddd2] pt-5"><span className="eyebrow">A practice</span><h3 className="mt-4 font-serif text-[25px] leading-tight">The five-minute page</h3><p className="mt-3 text-[13px] leading-6 text-[#72655a]">A gentle prompt for hearing what you already know.</p><button onClick={() => go('resources')} className="mt-5 font-mono text-[9px] uppercase tracking-[.15em] text-[#b76872]" data-testid="button-journal-practice">Explore resources</button></article><article className="border-t border-[#e7ddd2] pt-5"><span className="eyebrow">On books</span><h3 className="mt-4 font-serif text-[25px] leading-tight">A room of one's own, revisited</h3><p className="mt-3 text-[13px] leading-6 text-[#72655a]">Why the space we make for stories matters.</p><button onClick={() => go('books')} className="mt-5 font-mono text-[9px] uppercase tracking-[.15em] text-[#b76872]" data-testid="button-journal-books">Browse the books</button></article></div></div></section>
      <section id="gather" className="scroll-mt-20 border-y border-[#e7ddd2] bg-[#f7f1e9] px-6 py-28 lg:px-12 lg:py-32"><div className="mx-auto max-w-[1040px]"><div className="mb-12 text-center"><div className="eyebrow">Gather with me</div><h2 className="mt-4 font-serif text-[clamp(38px,5vw,62px)] leading-none tracking-[-.04em]">There is more room<br /><em className="text-[#b76872]">around a table.</em></h2><p className="mx-auto mt-5 max-w-[480px] text-[14px] leading-7 text-[#72655a]">Book clubs, conversations, launches, and quiet virtual rooms for readers who believe stories are better when shared.</p></div><div className="border-y border-[#e7ddd2]">{[['OCT 12', 'A conversation about Small Mercies', 'The Lantern Room · Asheville, NC'], ['NOV 03', 'An evening of new beginnings', 'Virtual gathering · 7:00 PM EST']].map(([date, title, place]) => <div key={date} className="grid gap-4 border-b border-[#e7ddd2] py-6 last:border-b-0 md:grid-cols-[110px_1fr_auto] md:items-center"><div className="font-mono text-[10px] tracking-[.16em] text-[#b76872]">{date}</div><div><h3 className="font-serif text-[22px]">{title}</h3><p className="mt-1 text-[13px] text-[#72655a]">{place}</p></div><button onClick={() => go('contact')} className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[.15em] hover:text-[#b76872]" data-testid={`button-rsvp-${date.toLowerCase()}`}>Reserve a place <ArrowUpRight size={14} /></button></div>)}</div></div></section>
      <section id="contact" className="scroll-mt-20 bg-[#3c2a22] px-6 py-28 text-[#fbf8f4] lg:px-12 lg:py-36"><div className="mx-auto grid max-w-[1100px] gap-16 lg:grid-cols-[.8fr_1.2fr]"><div><div className="eyebrow text-[#d8c79b]">The readers' circle</div><h2 className="mt-5 font-serif text-[clamp(40px,5vw,64px)] leading-[.98] tracking-[-.04em] text-[#fbf8f4]">A letter,<br /><em className="text-[#d89ca4]">occasionally.</em></h2><p className="mt-7 max-w-[370px] font-serif text-[17px] leading-7 text-[#ded2c6]">Receive reflections, new releases, and a little encouragement directly from Roselyn. No noise. Just something worth opening.</p><div className="mt-7 flex items-center gap-3 text-[#c7a164]"><Mail size={16} /><span className="font-mono text-[9px] uppercase tracking-[.16em]">A considered inbox</span></div></div><form onSubmit={(e) => { e.preventDefault(); if (newsletter.trim()) setNewsletterSent(true); }} className="flex flex-col justify-center"><label htmlFor="newsletter-email" className="font-mono text-[10px] uppercase tracking-[.15em] text-[#d8c79b]">Join the circle</label><div className="mt-5 flex border-b border-[#9b8877] pb-3"><input id="newsletter-email" type="email" required value={newsletter} onChange={(e) => setNewsletter(e.target.value)} placeholder="Your email address" className="min-w-0 flex-1 bg-transparent text-[17px] text-[#fbf8f4] placeholder:text-[#a99485] focus:outline-none" data-testid="input-newsletter-email" /><button type="submit" className="ml-4 text-[#d89ca4]" aria-label="Join the readers circle" data-testid="button-newsletter-submit"><Send size={19} /></button></div>{newsletterSent ? <p className="mt-5 font-serif text-[16px] text-[#d8c79b]" data-testid="status-newsletter-success">Thank you. Your first letter is on its way.</p> : <p className="mt-5 text-[12px] text-[#a99485]">You can leave anytime. I will never fill your inbox.</p>}<div className="mt-14 border-t border-[#665349] pt-6"><div className="font-mono text-[9px] uppercase tracking-[.15em] text-[#a99485]">For book clubs, press & speaking</div><button type="button" onClick={() => setMessageSent(true)} className="mt-3 flex items-center gap-2 font-serif text-[22px] text-[#fbf8f4] hover:text-[#d89ca4]" data-testid="button-contact-open">Start a conversation <ArrowUpRight size={17} /></button>{messageSent && <p className="mt-3 text-[13px] text-[#d8c79b]" data-testid="status-contact-success">Thank you. I will be in touch soon.</p>}</div></form></div></section>
    </main>
    <footer className="bg-[#2c211c] px-6 py-12 text-[#fbf8f4] lg:px-12"><div className="mx-auto max-w-[1240px]"><div className="grid gap-10 border-b border-[#665349] pb-10 md:grid-cols-[1.4fr_1fr_1fr]"><div><div className="flex items-center gap-3"><img src={logoAsset} alt="Gifford Publishing mark" className="h-11 w-11 rounded-full object-cover" /><span className="font-serif text-[18px]">Roselyn Gifford</span></div><p className="mt-5 max-w-[300px] text-[13px] leading-6 text-[#a99485]">Books for healing, resilience, hope, and the courage to become.</p></div><div><div className="eyebrow text-[#d8c79b]">Explore</div><div className="mt-5 flex flex-col items-start gap-3 text-[13px] text-[#ded2c6]"><button onClick={() => go('books')} data-testid="link-footer-books">Books</button><button onClick={() => go('about')} data-testid="link-footer-about">About Roselyn</button><button onClick={() => go('journal')} data-testid="link-footer-journal">Journal</button></div></div><div><div className="eyebrow text-[#d8c79b]">Keep in touch</div><div className="mt-5 flex items-center gap-4"><button className="text-[#ded2c6] hover:text-[#d89ca4]" aria-label="Instagram" data-testid="button-footer-instagram"><Instagram size={18} /></button><button onClick={() => go('contact')} className="text-[#ded2c6] hover:text-[#d89ca4]" aria-label="Email Roselyn" data-testid="button-footer-email"><Mail size={18} /></button></div></div></div><div className="flex flex-col justify-between gap-3 pt-6 font-mono text-[9px] uppercase tracking-[.13em] text-[#8e786a] md:flex-row"><span>© 2026 Gifford Publishing</span><span>Made for the readers who are still becoming</span></div></div></footer>
    {activeBook && <div className="fixed inset-0 z-40 flex items-center justify-center bg-[#3c2a22]/55 p-5 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={`${activeBook.title} details`}><div className="relative grid max-h-[90vh] w-full max-w-[680px] gap-8 overflow-auto bg-[#fbf8f4] p-7 shadow-2xl sm:grid-cols-[.7fr_1.3fr] sm:p-10"><button onClick={() => setActiveBook(null)} className="absolute right-4 top-4 rounded-full p-2 text-[#72655a] hover:bg-[#eee5da]" aria-label="Close book details" data-testid="button-close-book"><X size={18} /></button><div className="mx-auto"><BookCover book={activeBook} /></div><div className="flex flex-col justify-center"><div className="eyebrow">{activeBook.label}</div><h2 className="mt-4 font-serif text-[34px] leading-tight">{activeBook.title}</h2><p className="mt-4 font-serif text-[16px] italic leading-7 text-[#72655a]">{activeBook.subtitle}</p><p className="mt-5 text-[14px] leading-7 text-[#72655a]">{activeBook.detail}</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={() => { setActiveBook(null); go('contact'); }} className="bg-[#3c2a22] px-5 py-3 font-mono text-[9px] uppercase tracking-[.15em] text-[#fbf8f4]" data-testid="button-book-club-guide">Book club guide</button><button onClick={() => { setActiveBook(null); go('contact'); }} className="border border-[#3c2a22] px-5 py-3 font-mono text-[9px] uppercase tracking-[.15em]" data-testid="button-book-purchase">Find your copy</button></div></div></div></div>}
  </div><Toaster /></TooltipProvider></QueryClientProvider>;
}
export default App;